### ISSUE TITLE
FF puts buttons in two rows.

### ISSUE THREAD

**Issue by Erstus** [1Hyena/cryptograffiti#12]
In firefox, flexbox puts the last item(About tab button) on a next row.
![screen shot 2017-02-14 at 21 44 56](https://cloud.githubusercontent.com/assets/22116722/22946093/164915c4-f2ff-11e6-97b6-74b00883a15f.png)

**Comment by 1Hyena** [comment]
@Erstus 
Prolly because buttons lack styling so they use browser defaults which differ across browsers.

Whoever fixes this, make a pull request and upon successful merge I will send you 5 EUR/USD worth of bitcoins as a token of my gratitude.

**Comment by 1Hyena** [comment]
@Erstus 
should be fixed now, check it out and let me know if it is really so.

**Comment by Erstus** [comment]
Confirmed.
