### ISSUE TITLE
60€: Add QR code support

### ISSUE THREAD

**Issue by 1Hyena** [1Hyena/cryptograffiti#16]
When saving a message on the block chain and prompted with payment details, present a QR code so that payment could be made more easily with mobile devices.

**Comment by ghost** [comment]
I looked at the [specifications](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki) and it seemed there is no format for QR codes for paying to multiple addresses.

**Comment by 1Hyena** [comment]
@eq it's not a problem because cryptograffiti asks for a payment to a single address at first. it will later make a multisend based on that payment.

**Comment by 1Hyena** [comment]
Done as of commit 59c5a2039c50a53c57e9a98c23327a2c5fce654c
Can be closed now
