### ISSUE TITLE
150€ bounty: Scale images in accordance to browser font size

### ISSUE THREAD

**Issue by 1Hyena** [1Hyena/cryptograffiti#22]
The whole page is pretty responsive and reacts well to custom font sized defined by the user in their browser settings. However, currently images are not scaled in accordance to font size. When the user increased browser's font size to maximum then images still remain in their original size. This looks ugly and should be fixed.

**Comment by Erstus** [comment]
It's possible to give fixed heights to images in em units.
For example cg-title-img would have 'height: 4em;'
That would scale it proportionally with browser font size.(tested in firefox)
The same could be done for language buttons etc.
Not sure about images inside messages though.(variable sizes)

Btw. while testing i noticed in two places the text wasn't scaling either.
This was the case with contact info in about tab and tools tab upload button.

**Comment by 1Hyena** [comment]
@Erstus 
do it
