### ISSUE TITLE
Font unreadably small on chrome for android.

### ISSUE THREAD

**Issue by Erstus** [1Hyena/cryptograffiti#29]
Using rem units for font-size cause chrome for android to render text totally unreadable(too small) unless font-size is fixed in root element(html) with precise pixels. "html{font-size:12px}" would be fine, but removes the support for user-specified font size. Problem most-likely has to do with smart-phone high pixel density being compensated in a weird way. IMO chrome bug. Probably needs a pinpointed fix, because font-size works as expected on every other browser but chrome.

**Comment by Erstus** [comment]
Found the exact bug, that's responsible: https://bugs.chromium.org/p/chromium/issues/detail?id=696364#c32
My device language was Estonian, but when i changed it to English, everything rendered correctly. Other known language setting to cause a buggy render is Icelandic. Since it's a known bug in chrome, i guess we should not bother to find a fix.

**Comment by 1Hyena** [comment]
@Erstus nice find. Let's keep this issue open for a month and check back later.

**Comment by 1Hyena** [comment]
@Erstus is it still an issue?
