### ISSUE TITLE
Decode the Bitcoin whitepaper from the block chain

### ISSUE THREAD

**Issue by 1Hyena** [1Hyena/cryptograffiti#33]
Someone has encoded the original whitepaper of Bitcoin on the block chain. Since the Core development team and bitcoin.org has gone rogue trying to alter the original whitepaper of Satoshi Nakamoto to fit their central banker agenda it is important to make the true original easily available for the public. CryptoGraffiti.info should be capable of decoding this special TX that contains the Bitcoin's whitepaper.

https://bitcoin.stackexchange.com/questions/35959/how-is-the-whitepaper-decoded-from-the-blockchain-tx-with-1000x-m-of-n-multisi

Here is the TX that contains the whitepaper:
https://blockchain.info/tx/54e48e5f5c656b26c3bca14a8c95aa583d07ebe84dde3b7dd4a78f4e4186e713

**Comment by TrustyJAID** [comment]
In order to decode it you need to remove the length and checksum which correspond to the first 4 and 8 bytes of the transaction. The first 4 tell you the length of the total data required and the next 4 after that determine a crc32 checksum for the data. Once you know  the length you can crop the data after those 8 to the length specified and then perform a crc32 checksum on the second 4 bytes. If the checksum matches you have the correct PDF file and can open it without an issue.

Edit: [here](https://github.com/TrustyJAID/Blockchain-downloader/blob/master/reference/satoshi/Satoshi-Uploader.py) is the code that was used to upload the PDF and [here](https://github.com/TrustyJAID/Blockchain-downloader/blob/master/reference/satoshi/Satoshi-Downloader.py) is code written to download the PDF.

**Comment by 1Hyena** [comment]
@TrustyJAID thanks for the input! if this is really so simple I might slap the necessary code together on some free weekend ;)

**Comment by TrustyJAID** [comment]
Yeah it would be worth checking every transaction for it as there's a bunch of things inside that use this length and checksum. If it doesn't use it then you can just post the full data as is. I have found some transactions will show the length and checksum are correct but don't have any associated data just from how the data is structured but it's a simple little check to do.

**Comment by molecular** [comment]
Cool idea. We need something better to link to than bitcoin.com/bitcoin.pdf. cryptograffiti would be better.

What's this about a bounty? @1Hyena you want to be paid for this?

**Comment by 1Hyena** [comment]
@molecular no the bounty was the other way around, I was willing to pay to anyone who does these things for me. it wasn't very popular so I removed it.

the issue with this particular TX is that it's probably made by a miner because it exceeds the standard TX size limit of 100 000 bytes  ( whitepaper is larger than this ). Quite frankly I have so much stuff to do with cryptograffiti that I haven't still got to this issue.

**Comment by molecular** [comment]
ok. I'm just looking for a way to link the bitcoin paper that...

  * isn't based on some centralized service (like bitcoin.com/bitcoin.pdf)
  * is "clickable" for the average joe (does not involve running a python script)

I figured a cryptograffiti link could be a great compromise.

willing to chip in on the bounty.

**Comment by 1Hyena** [comment]
Alright, I will pay you 100 EUR worth of BSV if you make a PR that when applied will be capable of extracting the bitcoin.pdf from here:

https://bchsvexplorer.com/tx/54e48e5f5c656b26c3bca14a8c95aa583d07ebe84dde3b7dd4a78f4e4186e713

To do that, modify the `cg_read_extract_insight`, `cg_read_extract_blockchair` and `cg_read_extract_btc`  functions in `read.js` so that they are capable of decoding this particular TX. It should grab the PDF payload from the TX and return it as a hex string value of the `out_bytes` variable:

```js
return [out_bytes, op_return, time];
```

Since `out_bytes` is normally the concatenation of all the P2PKH outputs that are 20 bytes each, you must make sure that what you are returning has a length that is divisible by 20 (40 in case of a hex string). To do that, add zero padding to the end of the payload.

In the meantime, I will manually add this transaction to the cryptograffiti's database with the necessary metadata, so that the PDF could be actually displayed on screen. Let me know if you have any questions ;)

EDIT:

This is how you probably want to test your code:
https://cryptograffiti.info#54e48e5f5c656b26c3bca14a8c95aa583d07ebe84dde3b7dd4a78f4e4186e713.pdf

(replace the `https://cryptograffiti.info` part with the file path in your local file system, to test it offline)

Example of an already existing PDF from the block chain that can be displayed by cryptograffiti:

https://cryptograffiti.info/#b4f537bc536c392d425af0693e3282bbf697df01debeeaf7f9918b93af6bdd14.pdf

**Comment by 1Hyena** [comment]
I have now manually added this TX to cryptograffiti's database. If you want to see all pdf files, go here:

https://cryptograffiti.info/#mimetype:application/pdf

The one containing bitcoin's whitepaper is here:

https://cryptograffiti.info/#697515

it is now returned by the API with the mimetype `application/pdf`, should be all that is needed in order to make it display in the read tab as a pdf, once the changes described in my previous post are implemented.

**Comment by molecular** [comment]
I can see an example pdf, but the bitcoin.pdf (697515) isn't "downloadable"?

![image](https://user-images.githubusercontent.com/589745/62688441-257c9f00-b9c9-11e9-93be-68b90f18a3f0.png)

 Is this the expected behaviour at this point?

**Comment by 1Hyena** [comment]
@molecular the bitcoin.pdf does not decode because it is encoded in a different way than the example.pdf. this issue is about fixing it by implementing a new decoder solely for the purpose of decoding bitcoin.pdf.
