### ISSUE TITLE
Existing transaction no longer decoded

### ISSUE THREAD

**Issue by rjw245** [1Hyena/cryptograffiti#75]
In April 2019, I had uploaded this transaction containing a PGP-signed text file:

https://cryptograffiti.info/#48e786b61aa07673a90ad84e86c58b0a5ef3c52a1d9b304927a22f201fddadf0

But navigating to that page only shows the multimedia wall.
Has support for binary data been pulled?

**Comment by 1Hyena** [comment]
As of version 2.0 this functionality is indeed no longer available.
