### ISSUE TITLE
50€ bounty: Favicon needed

### ISSUE THREAD

**Issue by 1Hyena** [1Hyena/cryptograffiti#8]
Design and add a desirable favicon.ico to the project.

**Comment by 1Hyena** [comment]
@Erstus I guess you can attach here also the list of those preliminary favicons. I don't remember which one we picked out to be the best one.

**Comment by 1Hyena** [comment]
10 USD worth of bitcoins as a token of my gratitude to anyone successfully solving this issue.

**Comment by Erstus** [comment]
Here are ideas for favicon so far. Green arrow-bird (bottom row) is my favorite so far.
![cryptograffiti](https://cloud.githubusercontent.com/assets/22116722/24180598/6eea18d8-0ebe-11e7-8903-28d6aff80e25.png)

**Comment by 1Hyena** [comment]
@Erstus yes it is good. I like the font style also. The second from the top is also a good idea, having 2 separate lines beginning with the logo. Internally I use cg_ prefix so it makes sense to have cg in the logo. Just the favicon part is a little hard to understand how the letters C and G appear on it.

**Comment by Erstus** [comment]
Here's a new title image:
![banner](https://user-images.githubusercontent.com/22116722/34448178-beb310e0-ecf3-11e7-8873-180d7143df50.png)
And a favicon: ![favicon](https://user-images.githubusercontent.com/22116722/34448182-c31892fe-ecf3-11e7-9d6d-c1990949f3b3.gif)
I've got vector(.svg) for this design, so resolution can be made responsive.

**Comment by 1Hyena** [comment]
@Erstus 
nice, give me your bitcoin cash receiving address and I'll send you the bounty
